pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = 'dockerhub-maorsh6-credentials'
        IMAGE_NAME = 'maorsh6/ci-cd-app'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/maorsh1/devops-portfolio.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir('ci-cd-app') {
                        bat 'docker build -t "maorsh6/ci-cd-app:latest" .'
                    }
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', "${DOCKERHUB_CREDENTIALS}") {
                        docker.image("${IMAGE_NAME}:latest").push()
                    }
                }
            }
        }

        stage('Deploy to Minikube') {
            steps {
                script {
                    dir('ci-cd-app') {
                        bat 'set KUBECONFIG=C:\\Users\\97255\\.kube\\config && kubectl apply -f k8s/deployment.yaml'
                        bat 'set KUBECONFIG=C:\\Users\\97255\\.kube\\config && kubectl apply -f k8s/service.yaml'
                    }
                }
            }
        }
    }
}
